# Generated by Django 6.0.3 on 2026-03-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_alter_collectioncenter_city_and_more'),
        ('core_order', '0003_delivery_latitude_delivery_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='pickup_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.collectioncenter'),
        ),
    ]
