# Generated by Django 6.0.3 on 2026-03-26 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0010_alter_collectioncenter_city_and_more'),
        ('core_order', '0004_alter_delivery_pickup_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collection_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.collectioncenter'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('sent_to_collection', 'Sent To Collection Center'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=50),
        ),
    ]
