# Generated by Django 6.0.3 on 2026-03-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_collectionorder_vendororder'),
        ('core_order', '0006_order_delivery_date_order_order_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerOrderBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cutoff_time', models.DateTimeField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='longitude',
        ),
        migrations.AddField(
            model_name='delivery',
            name='source_type',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('collection_center', 'Collection Center')], default='farmer', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.seller'),
        ),
        migrations.AddField(
            model_name='order',
            name='flow_type',
            field=models.CharField(choices=[('vendor', 'Vendor Delivery'), ('farmer', 'Farmer via Collection Center')], default='farmer', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='pickup_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.collectioncenter'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('farmer_assigned', 'Farmer Assigned'), ('sent_to_collection', 'Sent To Collection'), ('at_collection_center', 'At Collection Center'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=50),
        ),
        migrations.CreateModel(
            name='FarmerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.seller')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_order.orderitem')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_order.farmerorderbatch')),
            ],
        ),
    ]
