# Generated by Django 6.0.3 on 2026-03-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_order', '0007_farmerorderbatch_remove_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='source_type',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('collection_center', 'Collection Center')], default='collection_center', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('picked', 'Picked'), ('delivered', 'Delivered')], default='assigned', max_length=50),
        ),
    ]
