# Generated by Django 6.0.3 on 2026-03-31 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_collectionorder_vendororder'),
        ('core_order', '0008_alter_delivery_source_type_alter_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='core_order.order')),
                ('vendor', models.ForeignKey(limit_choices_to={'seller_type': 'vendor'}, on_delete=django.db.models.deletion.CASCADE, to='core_app.seller')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'seller_type': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='core_app.seller')),
            ],
            options={
                'unique_together': {('farmer', 'month')},
            },
        ),
    ]
