# Generated by Django 6.0.3 on 2026-04-02 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_collectionorder_vendororder'),
        ('core_order', '0009_admincommission_farmersalary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collection_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_app.collectioncenter'),
        ),
    ]
