# Generated by Django 6.0.3 on 2026-03-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_type',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('vendor', 'Vendor')], default='farmer', max_length=20),
        ),
    ]
