# Generated by Django 6.0.3 on 2026-03-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_remove_otp_phone_otp_expire_at_otp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('farmer', 'Farmer'), ('vendor', 'Vendor'), ('delivery', 'Delivery Boy'), ('collection_center', 'Collection Center')], max_length=20),
        ),
    ]
