# Generated by Django 6.0.3 on 2026-03-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_user_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectioncenter',
            name='location',
        ),
        migrations.AddField(
            model_name='collectioncenter',
            name='address',
            field=models.TextField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='collectioncenter',
            name='city',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='collectioncenter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='collectioncenter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='collectioncenter',
            name='state',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
