# Generated by Django 6.0.3 on 2026-03-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_remove_collectioncenter_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncenter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collectioncenter',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
