# Generated by Django 6.0.3 on 2026-03-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0011_subscription'),
        ('core_order', '0006_order_delivery_date_order_order_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('assigned', 'Assigned to Delivery')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.collectioncenter')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_order.order')),
            ],
        ),
        migrations.CreateModel(
            name='VendorOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('packed', 'Packed'), ('ready', 'Ready')], max_length=20)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core_order.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.seller')),
            ],
        ),
    ]
