# Generated by Django 6.0.3 on 2026-06-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0016_deliveryboyprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryBoyProfile',
        ),
    ]
