# Generated by Django 6.0.3 on 2026-03-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_order', '0005_alter_order_collection_center_alter_order_status'),
        ('core_product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionCenter',
        ),
    ]
