# Generated by Django 6.0.3 on 2026-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_product', '0002_delete_collectioncenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('grocery', 'Grocery'), ('vegetable', 'Vegetable')], default='vegetable', max_length=20),
        ),
    ]
