# Generated by Django 6.0.3 on 2026-04-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_product', '0003_category_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='farmer',
            new_name='seller',
        ),
    ]
