# Generated by Django 6.0.3 on 2026-04-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_product', '0004_rename_farmer_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='harvest_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_in_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='base_price_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
